---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-client-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-client-service
  template:
    metadata:
      labels:
        app: my-client-service
    spec:
      containers:
        - name: my-client-service
          image: "registry.gitlab.com/aletundo/cloud-computing-lab:lecture01-es04-client"
          imagePullPolicy: Always
          ports:
            - name: port
              containerPort: 5000
              protocol: TCP
          env:
            - name: BACKEND_URL
              value: http://nginx:8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-client-service
  namespace: "default"
  labels:
    app: my-client-service
spec:
  type: ClusterIP
  selector:
    app: my-client-service
  ports:
    - name: port
      port: 5000
      targetPort: 5000
      protocol: "TCP"
